name = "sheet-scribe-ai-lab"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "npm install && npm run build"
cwd = "."

[env.production]
VITE_BACKEND_URL = "https://superservercode.onrender.com"
